---
pi_hostname: "radio"
url_to_show: "https://radio.svsticky.nl"

wifi_networks:
  - ssid: "Woestgaafsecure"
    password: "fantazero"

  - ssid: "Woestgaafsecure (5GHz)"
    password: "fantazero"

  - ssid: "Woestgaafsecure Gamehall"
    password: "fantazero"

unattended_upgrades:
  security: true
  all: true
