---
- name: "reload sshd"
  service:
    name: "sshd"
    state: "reloaded"

- name: "systemctl --user daemon-reload"
  systemd:
    scope: "user"
    daemon_reload: true
  become_user: "pi"

- name: "systemctl daemon-reload"
  systemd:
    daemon_reload: true
