---
- name: "install packages required for graphical environment"
  apt:
    name:
      - "arandr"
      - "cec-utils"
      - "feh"
      - "firefox-esr"
      - "i3"
      - "libcec4"
      - "libcec4-dev"
      - "python-libcec"
      - "lightdm"
      - "mplayer"
      - "rxvt-unicode"
      - "x11-xserver-utils"
      - "xdotool"
    state: "present"

- name: "copy wallpapers"
  copy:
    src: "templates/home/pi/Wallpapers"
    dest: "/home/pi"
    owner: "pi"
    group: "pi"

- name: "install systemd directory"
  file:
    path: "/home/pi/.config/systemd/user"
    state: "directory"
    owner: "pi"
    group: "pi"

- name: "install wallpaper changer"
  template:
    src: "home/pi/.config/systemd/user/{{ item }}.j2"
    dest: "/home/pi/.config/systemd/user/{{ item }}"
    owner: "pi"
    group: "pi"
  loop:
    - "set-wallpaper@.timer"
    - "set-wallpaper@.service"

  notify: "systemctl --user daemon-reload"

- meta: "flush_handlers"

- name: "enable wallpaper changer timer"
  systemd:
    scope: "user"
    name: "set-wallpaper@error.timer"
    enabled: "yes"
    state: "started"

  become_user: "pi"

- name: "create xorg.conf.d"
  file:
    path: "/etc/X11/xorg.conf.d"
    state: "directory"
    owner: "root"
    group: "root"

- name: "disable DPMS"
  template:
    src: "etc/X11/xorg.conf.d/10-no-screensaver.conf.j2"
    dest: "/etc/X11/xorg.conf.d/10-no-screensaver.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "place custom LightDM config"
  template:
    src: "etc/lightdm/lightdm.conf.j2"
    dest: "/etc/lightdm/lightdm.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "ensure i3 directory exists"
  file:
    path: "/home/pi/.config/i3"
    state: "directory"
    owner: "pi"
    group: "pi"

- name: "place i3 config"
  template:
    src: "home/pi/.config/i3/config.j2"
    dest: "/home/pi/.config/i3/config"
    owner: "pi"
    group: "pi"
