---
- name: "install system management packages"
  apt:
    name:
      - "aptitude"
      - "git"
      - "tmux"
    state: "present"

- name: "ensure persistent log directory exists"
  file:
    path: "/var/log/journal"
    state: "directory"
    owner: "root"
    group: "systemd-journal"
    mode: "02755"

- name: "update all packages"
  apt:
    cache_valid_time: 3600
    upgrade: "full"
  tags:
    - "slow"

- name: "install remote-trigger script"
  template:
    src: "usr/local/bin/remote-trigger.j2"
    dest: "/usr/local/bin/remote-trigger"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "allow remote-trigger to sudo"
  template:
    src: "etc/sudoers.d/030_remote-trigger.j2"
    dest: "/etc/sudoers.d/030_remote-trigger"
    owner: "root"
    group: "root"
    mode: "0440"

- name: "ensure remote-trigger user exists"
  user:
    name: "remote-trigger"
    state: "present"
    password_lock: "yes"
    shell: "/bin/bash"

- name: "ensure ~remote-trigger/.ssh exists"
  file:
    path: "/home/remote-trigger/.ssh"
    state: "directory"
    owner: "remote-trigger"
    group: "remote-trigger"
    mode: "0755"

- name: "copy remote-trigger's authorized_keys"
  template:
    src: "home/remote-trigger/.ssh/authorized_keys.j2"
    dest: "/home/remote-trigger/.ssh/authorized_keys"
    owner: "remote-trigger"
    group: "remote-trigger"
    mode: "0644"
