---
# Needed because of Ansible issue #25414
- name: "check if unattended-upgrades is not in progress"
  shell:
    "while fuser /var/lib/dpkg/lock; do sleep 1; done;"
  become: true
  changed_when: false

- name: "install common utilities"
  apt:
    name:
      - "aptitude"
      - "htop"
      - "unattended-upgrades"
      - "haveged"
    state: "present"

# uncomment in case of merge list error
# https://www.ihaveapc.com/2011/05/how-to-fix-problem-with-mergelist-varlibaptlists-error-in-ubuntu-11-04/
#- name: "remove merge list"
#  command: "rm /var/lib/apt/lists/* -vf"

- name: "update all packages"
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 100

- name: "configure unattended-upgrades"
  template:
    src: "templates/{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - "etc/apt/apt.conf.d/50unattended-upgrades"
  notify:
    - "systemctl daemon-reload"


