---
- hostname:
    name: "{{ pi_hostname }}"

- locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "nl_NL.UTF-8"

- name: "set timezone"
  timezone:
    name: "Europe/Amsterdam"
