---
- hostname:
    name: "{{ pi_hostname }}"

- name: "place /boot/config.txt"
  template:
    src: "boot/config.txt.j2"
    dest: "/boot/config.txt"

- name: "set timezone"
  timezone:
    name: "Europe/Amsterdam"

- name: "place /etc/hosts"
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
