---
- hostname:
    name: "{{ pi_hostname }}"

- name: "place /boot/config.txt"
  template:
    src: "boot/config.txt.j2"
    dest: "/boot/config.txt"

- name: "set timezone"
  timezone:
    name: "Europe/Amsterdam"

- name: "place /etc/hosts"
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"

- name: "install systemd services and timer"
  template:
    src: "etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: "root"
    group: "root"

  with_items:
    - "play-sound@.service"
    - "bier-uur.timer"
  notify: "systemctl daemon-reload"

- meta: "flush_handlers"

- name: "enable startup notification"
  systemd:
    name: "{{ item }}"
    enabled: "yes"

  with_items:
    - "bier-uur.timer"

- name: "remove timed-shutdown"
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: "absent"

  with_items:
    - "timed-shutdown.timer"
    - "timed-shutdown.service"

  notify: "systemctl daemon-reload"


